#!/bin/bash -e

## load defaults
. ./common.sh

## collect modules list
MODULES="tcl tk thread tcllib tklib itcl itk tkimg rbc tkpath tbcload bwidget iwidgets tkcon gse tcludp tktable"

## architecture i686/x86_64
if [ "$BARCH" == "i686" ]; then
    MODULES+=""
else
    MODULES+=" pgtcl"
fi

## platform linux/windows
if [ -z "$WINDIR" ]; then
    MODULES+=" xcursor"
fi

## start to compile
for MODULE in $MODULES; do
    bash -e ./compile-${MODULE}.sh "$@"
    echo ""
done

## fini
if [ -z "$SW_DEBUG" ]; then
    echo "** Finished compile-base release."
else
    echo "** Finished compile-base debug."
fi
