#!/bin/bash -e

## load defaults
. ./common.sh

## collect modules list
## boost dsp
MODULES="fftw except tktable"
#"critcl zeromq tclzmq"

## architecture i686/x86_64
if [ "$BARCH" == "i686" ]; then
    MODULES+=""
fi

## platform linux
if [ -z "$WINDIR" ]; then
    MODULES+=" vxi hpib"
fi

## start to compile
for MODULE in $MODULES; do
    bash -e ./compile-${MODULE}.sh "$@"
    echo ""
done

## fini
if [ -z "$SW_DEBUG" ]; then
    echo "** Finished compile-extras release."
else
    echo "** Finished compile-extras debug."
fi

